version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:15
    container_name: poc-airflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_pass
      POSTGRES_DB: retail_dwh
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:Z
    ports:
      - "55432:5432"

  airflow:
    build: .
    image: poc-airflow:latest
    container_name: poc-airflow
    restart: unless-stopped
    depends_on:
      - postgres
    user: "0:0"

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow_pass@postgres:5432/retail_dwh
      _AIRFLOW_WWW_USER_USERNAME: "admin"
      _AIRFLOW_WWW_USER_PASSWORD: "admin"

    volumes:
      - ./airflow/dags:/opt/airflow/dags:Z
      - ./airflow/logs:/opt/airflow/logs:Z
      - ./airflow/plugins:/opt/airflow/plugins:Z
      - ./data:/opt/airflow/data:Z
      - ./dbt/retail_project:/opt/dbt/retail_project:Z
      - ./dbt_config:/root/.dbt:Z

    ports:
      - "8082:8080"

    command: >
      bash -c "
        airflow db upgrade &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin || true;
        airflow scheduler &
        airflow webserver --port 8080
      "
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"

